[project]
name = "gaaml"
version = "0.1.1"
description = "Genetic Algorithm-based AutoML"
authors = [{ name="Szymon Wasążnik", email="zlog@protonmail.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "tqdm",
  "numpy",
  "keras",
  "matplotlib",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# [tool.pytest.ini_options]
# pythonpath = ["src"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
gaaml = ["py.typed"]
